name: Publish Docker image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/docsabot:${{ env.VERSION }} .
          docker tag ghcr.io/${{ github.repository_owner }}/docsabot:${{ env.VERSION }} ghcr.io/${{ github.repository_owner }}/docsabot:latest
          docker push ghcr.io/${{ github.repository_owner }}/docsabot:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/docsabot:latest
